### ISSUE TITLE
Broken in 3.9

### ISSUE THREAD

**Issue by giuseppebergman** [joshwayne/jw-sketch-plugins#5]
Hi, 
It does no longer work in 3.9 final. A fix would be great!
Thank you for you work.

**Comment by giuseppebergman** [comment]
To be more specific, it creates a new layer with the first line only, leave the original layer untouched, then stops.
Here's the log:
```
22/07/2016 11:16:45,367 Split Text Lines to Layers [jw] (Sketch Plugin)[945]: TypeError: undefined is not a function (evaluating 'newFrame.addY_(  (lineHeight * j))')
line: 26
sourceURL: /Users/…/Library/Application Support/com.bohemiancoding.sketch3/Plugins/- Texte/Split Text Lines to Layers [jw].sketchplugin
column: 19
```

**Comment by joshwayne** [comment]
Fixed! Thanks for the heads up!
